language: node_js

cache:
  npm: true

node_js:
  - "10"
  - "12"
  - "14"

script:
  - npm run eslint
  - npm run test-cov

after_script:
  - npm install coveralls
  - nyc report --reporter=text-lcov | coveralls

